include: package:flutter_lints/flutter.yaml

# Rules for linter
linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_is_not_empty: true
    always_declare_return_types: true
    avoid_relative_lib_imports: true
    sort_child_properties_last: true
    require_trailing_commas: true
    use_full_hex_values_for_flutter_colors: true
    use_enums: true
    avoid_bool_literals_in_conditional_expressions: true